sudo: required
dist: trusty

language: php

env:
  global:
    - NO_INTERACTION=1
    - TEST_TIMEOUT=120

matrix:
  allow_failures:
    - php: nightly

  include:
    - php: 7.2
    - php: 7.2
      env: TEST_PHP_ARGS=-m

    - php: nightly
#    - php: nightly
#      env: TEST_PHP_ARGS=-m

before_install:
  - phpize && ./configure && make

script:
  - sh -c "make test | tee result.txt"
  - sh test-report.sh

addons:
  apt:
    packages:
      - valgrind
